name: HelpTicket
main: net.ghostrealms.helpticket.HelpTicketMain
version: 13.02.06
author: Ghost Realms Network
authors: [Rmarmorstein, vanZeben]
description: This plugin is used for players to log problems, requests and complaints.
website: http://GhostRealms.net
depend: [DeityAPI]
commands:
  Ticket:
        aliases: [pe]